<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartLLM.Telemetry.Core\SmartLLM.Telemetry.Core.csproj" />
    <ProjectReference Include="..\..\src\SmartLLM.Telemetry.Tokenizer\SmartLLM.Telemetry.Tokenizer.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
</Project>
